blog/blog/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page ,name ='home'),
    path('posts/',include('posts.urls')),
    path('user/',include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.posts_list , name='list'),
    path('<slug:slug>', views.post_page , name='page'),
    path('new-post/', views.post_new , name='new_post'),
]

blog/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register_view , name='register'),
    path('login/', views.login_view , name='login'),
    path('logout/', views.logout_view , name='logout'),
 
]

blog/posts/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default="default.png" , blank = True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
    
    def __str__(self):
        return self.title

blog/user/models.py
from django.db import models

# Create your models here.

blog/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    
    class Meta:
        model = models.Post
        fields = ('title','body','slug','image')
        
        
    

blog/blog/views.py
from django.shortcuts import render

def home_page(request):
    return render(request ,'home.html')

blog/posts/views.py
from django.shortcuts import render , redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def posts_list(request):
    posts= Post.objects.all()
    return render(request, 'posts/posts_list.html',{'posts':posts})

def post_page(request, slug):
    post = Post.objects.get(slug= slug)
    return render(request,'posts/post_page.html',{'post':post} )


@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list') 
        
    else:
        form = forms.CreatePost()
        
    return render(request, 'posts/new_post.html',{'form':form})

blog/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login,logout

def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts:list")
    else:
        form = UserCreationForm()

    return render(request, 'user/register.html', {'form': form})


def login_view(request):
    if request.method =="POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            login(request,form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            
            else:
                return redirect("posts:list")
        
    else:
        form = AuthenticationForm()

    return render(request,"user/login.html" ,{"form":form})
    
    
def logout_view(request):
    if request.method =="POST":
        logout(request)
    return redirect("posts:list")

blog/posts/templates/posts/new_post.html
{% extends "layout.html" %}


{% block title %}
    New post
{% endblock %}


{% block main %}
    <h1 class="left-2">New Post</h1>
    <form action="{% url 'posts:new_post'%}" method="POST" enctype = "multipart/form_data">
        {% csrf_token %}
        {{form}}

        <button>Add Post</button>
    </form>

{% endblock %}

blog/posts/templates/posts/post_page.html
{% extends "layout.html" %}


{% block title %}
    {{post.title}}
{% endblock %}


{% block main %}
    <h1 class="left-2">{{post.title}}</h1>
    <h2>{{post.body}}</h2>
    <p>{{ post.date }} by {{ post.author }}</p>

    

    <section>
        <img class="rounded-3xl size-72" src="{{post.image.url}}" alt="{{post.title}}">
    </section>
{% endblock %}

blog/posts/templates/posts/posts_list.html
{% extends 'layout.html'%}
{% comment %}
{% block title %}
    Posts List
{% endblock %}

{% block main %}

    {% for post in posts %}
    <a href="{% url 'posts:page' slug=post.slug%}"><h1>{{post.title}} by {{post.author}}</h1></a>
    
    
    {% endfor %}

    <br>
    <br>

    {% if user.is_authenticated%}
        <a href="{%url 'posts:new_post'%}"> ADD NEW POST</a>
    {% endif %}
{% endblock %} {% endcomment %}



{%block title%}
  POSTS
{%endblock%}

{%block main%}
  <section>
    <h1>
      Post List
    </h1>
    {% for post in posts%}
      <article>
        <h2>
          <a href="{% url 'posts:page' slug=post.slug%}">{{ post.title }}</a></h2>
          <a href=""></a>
       
      </article>
    {% endfor %}

    <br>
    <br>
    <br>

    {% if user.is_authenticated%}
    <a href="{%url 'posts:new_post'%}"> ADD NEW POST</a>
    {% endif %}
  </section>
{%endblock%}

blog/templates/home.html
{% extends 'layout.html'%}


{% block title %}
    Home
{% endblock %}

{% block main %}
    <h1>Welcome to Blogging Page</h1>

    <p>This is the website created for user to share the experience of their life with the help of blogging.</p>
{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
{% load static tailwind_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} THIS IS THE TITLE OHH!! {% endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    {% tailwind_css %}
</head>
<body>
    
    <nav class ="bg-cyan-600 rounded-2xl">
        <a href="{% url 'home' %}">Home</a>|
        <a href="{% url 'posts:list'%}">Posts</a>|

        {% if user.is_authenticated%}

            <form action="{% url 'user:logout'%}" method = 'post'>
             {% csrf_token %}
            <button class="inline">Logout</button>
        </form>   

        {% else %}
        <a href="{% url 'user:register'%}">Register</a>|
        <a href="{% url 'user:login'%}">Login</a>|


        {% endif %}

    </nav>


    {% block main%}
        this is the main block of the templates
    {%endblock%}
    
</body>
</html>

blog/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

blog/user/templates/user/login.html
{%extends 'layout.html'%}

{%block title%}
  login UsER
{%endblock%}

{%block main%}

    <h1>
      Login user List
    </h1>
    <form action="/user/login/" method= "post">
      {% csrf_token %}
      {{form}}
      {% if request.GET.next %}
        <input type="hidden" name = "next" value = "{{request.GET.next}}">

      {% endif %}
      <button>Submit</button>
    </form>



{%endblock%}

blog/user/templates/user/register.html
{%extends 'layout.html'%}

{%block title%}
  REGISTER UUSER
{%endblock%}

{%block main%}

    <h1>
      USER List
    </h1>
    <form action="/user/register/" method= "post">
      {% csrf_token %}
      {{form}}
      <button>Submit</button>
    </form>



{%endblock%}